### ISSUE TITLE
Patching python bindings does not work with liblinear v2.1

### ISSUE THREAD

**Issue by AdamFonagy** [recski/HunTag#10]
Dear Gábor,

when I tried to patch liblinear.py in the python subdir of liblinear installation folder according to you description I haven't got any result. The patch program didn't terminate at all, neither error message nor any changes in liblinear.py file.

I use Ubuntu 14.04 LTS. I downloaded and installed liblinear 2.1 which was released on September 27, 2015.

By the way manually I could merge your code changes from the patch file into liblinear.py

Best regards,
Ádám Fónagy

**Comment by recski** [comment]
Hi, thanks for reporting!
So far I failed to reproduce the problem - although I haven't tried using this latest liblinear version before, I had no problems patching it:
```
recski@recski:~/sandbox/liblinear-2.1/python$ patch < ~/sandbox/HunTag/liblinear.patch 
patching file liblinear.py
Hunk #1 succeeded at 57 with fuzz 2 (offset 15 lines).
```
And then huntag also seems to work fine.

@zseder any thoughts?

**Comment by zseder** [comment]
Hi,
I couldn't reproduce the issue either. Can you show us how you call `patch`?

**Comment by AdamFonagy** [comment]
Hi, it seems I used patch in a wrong way. Simply I call ```patch``` like this:

```
patch liblinear.patch
```
Using the snippet @recski wrote I could patch the liblinear.py file.
Sorry for confusing.
